### ISSUE TITLE
Release version 0.3

### ISSUE THREAD

**Issue by delgadom** [RhodiumGroup/docker_images#61]
Placeholder for next minor release priorities

## Goals
* Make using the cluster easier
  * [ ] Improve cluster creation helpers in `rhg_compute_tools`
  * [ ] Add `xr.from_delayed` functions to `rhg_compute_tools`
* Create cluster tutorials & tools for viewing them
  * [x] create [binder repo]()
  * [ ] develop cluster usage tutorials (that work on binder?)
  * [x] create [rhg_compute_tools docs]()
  * [ ] add docs on cluster usage, API docs for get_worker and other tools
* Add packages
  * [ ] geopy

### In this package
* [ ] #60 - add geopy
* [ ] #53  - figure out how to update pip

### Dependencies
* [ ] RhodiumGroup/rhg_compute_tools#8 - env variables in get_worker
* [ ] RhodiumGroup/rhg_compute_tools#3 - add pre-configured workers
* [ ] RhodiumGroup/rhg_compute_tools#12 - add xarray.from_delayed
* [ ] ClimateImpactLab/climate_toolbox#14 - add spatial nearest neighbor
